# Site settings
title: The Nerds 
index_title: test # same as title in index.html file, so that custom description can be set in page.html layout.
blog_title: Development Blog
header-img: img/home-bg.jpg
email: max@meldrum.se
description: "meldrum"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
#url: http://url.com #only used in disque comments for now
#disqus_url: url.com # disque comments are broken if you send http:// along with url
github_username:  test1ma3
email_username:  max@meldrum.se
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
