# Site settings
title: 
index_title: Young Ambitious People # same as title in index.html file, so that custom description can be set in page.html layout.
blog_title: Development Blog
header-img: img/home-bg.jpg
email: info@yappl.se
description: "Developer team"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url: http://yappl.se #only used in disque comments for now
disqus_url: teamyappl-github-io.disqus.com # disque comments are broken if you send http:// along with url
github_username:  yappl
email_username:  info@yappl.se
copyright_name: Yappl
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
